# What Is NumPy ?

### NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

In [1]:
#Let Get Started !

In [2]:
import numpy as np #importing numPy 

In [6]:
myarr = np.array([[3, 6, 32, 7]], np.int32)

In [4]:
myarr

array([ 3,  6, 32,  7])

In [7]:
#getting elements
myarr[0,1]

6

In [8]:
myarr.shape

(1, 4)

In [9]:
myarr.dtype

dtype('int32')

In [10]:
myarr[0,1] = 45 #changing element

In [11]:
myarr

array([[ 3, 45, 32,  7]])

In [12]:
listarr = np.array([[1,2,3], [5,8,9], [91,23,69], [0,3,1]])

In [13]:
listarr

array([[ 1,  2,  3],
       [ 5,  8,  9],
       [91, 23, 69],
       [ 0,  3,  1]])

In [14]:
listarr.shape

(4, 3)

In [16]:
listarr.size

12

In [17]:
listarr.dtype

dtype('int32')

In [18]:
np.array({32,34.2,56})

array({32, 34.2, 56}, dtype=object)

In [19]:
zeros = np.zeros((2, 5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
rng = np.arange(100)

In [23]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
lspace = np.linspace(1,54,4)

In [28]:
lspace

array([ 1.        , 18.66666667, 36.33333333, 54.        ])

In [29]:
lspace.dtype

dtype('float64')

In [30]:
emp = np.empty((4,6))

In [31]:
emp

array([[8.42282004e-312, 7.60861095e-322, 0.00000000e+000,
        0.00000000e+000, 7.56599806e-307, 1.15998412e-028],
       [4.31603868e-080, 1.94919985e-153, 1.35717430e+131,
        8.48576822e-096, 1.81148490e-152, 8.09244594e-153],
       [6.03108707e-154, 6.01391519e-154, 8.06374122e-096,
        1.20092377e+141, 6.01347002e-154, 6.03104155e-154],
       [1.95360725e-109, 4.90900643e+252, 1.94918511e-153,
        6.32672800e+180, 4.74483502e+170, 4.59210323e-072]])

In [32]:
emp_like = np.empty_like(lspace)

In [33]:
emp_like

array([ 1.        , 18.66666667, 36.33333333, 54.        ])

In [34]:
ide = np.identity(45)

In [35]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [36]:
ide.shape

(45, 45)

In [38]:
arr= np.arange(99)

In [39]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr = arr.reshape(3, 33)

In [42]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [45]:
arr = arr.ravel()
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [47]:
arr.shape

(99,)

In [52]:
x = [[1,2,3], [4,5,6], [7,1,0]]

In [53]:
arr = np.array(x)

In [54]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
arr.sum(axis=0)gi

array([12,  8,  9])

In [56]:
arr.sum(axis=1)

array([ 6, 15,  8])